---
name: List-AllUtils
version: 0.02
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Combines List::Util and List::MoreUtils in one bite-sized package
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  List::MoreUtils: 0.22
  List::Util: 1.19
  perl: 5.008
configure_requires:
  Module::Build: 0.35
provides:
  List::AllUtils:
    file: lib/List/AllUtils.pm
    version: 0.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
