
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
ARRAYn
BLOCK's
EXPR
KVLIST
firstidx
firstval
lastidx
lastval
maxstr
minmax
minstr
natatime
notall
pairfirst
pairgrep
pairkeys
pairmap
pairvalues
specialisations
thusly
uniq
util
DROLSKY
DROLSKY's
Rolsky
Rolsky's
Dave
autarch
lib
List
AllUtils
